CREATE ROLE arsenalum_sd_users_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    CREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_users_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_sd_operator WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_operator WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_owners_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_nomenclatures_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_product_types_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_reasons_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_units_editor WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;
CREATE ROLE arsenalum_service WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;